for i=1:36
    figure(i)
plot(Sumpuknwths(:,i))
hline1 = refline([0 max(Sumpuknwths(:,i))]);
hline1.Color='r';
hline2 = refline([0 min(Sumpuknwths(:,i))]);
hline2.Color= 'y';
end
for i=1:37
    figure(i+36)
    plot(HRSG(:,i))
hline1 = refline([0 max(HRSG(:,i))]);
hline1.Color='r';
hline2 = refline([0 min(HRSG(:,i))]);
hline2.Color= 'y';
end
for i=1:12
    figure(i+73)
    plot(AERIOSTROVILOS(:,i))
hline1 = refline([0 max(AERIOSTROVILOS(:,i))]);
hline1.Color='r';
hline2 = refline([0 min(AERIOSTROVILOS(:,i))]);
hline2.Color= 'y';
end
%figures Sumpuknwths
figure(1)
title('1h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Plant MW(NET)')
legend({'main graph','max(Sumpuknwths(:,1))','min(Sumpuknwths(:,1))'},'Location','southwest')
figure(2)
title('2h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('GasTurbine(MW)')
legend({'main graph','max(Sumpuknwths(:,2))','min(Sumpuknwths(:,2))'},'Location','southwest')
figure(3)
title('3h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('SteamTurbine(MW)')
legend({'main graph','max(Sumpuknwths(:,3))','min(Sumpuknwths(:,3))'},'Location','southwest')
figure(4)
title('4h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Ambient Humidity(%)')
legend({'main graph','max(Sumpuknwths(:,4))','min(Sumpuknwths(:,4))'},'Location','southwest')
figure(5)
title('5h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Ambient Temperature')
legend({'main graph','max(Sumpuknwths(:,5))','min(Sumpuknwths(:,5))'},'Location','southwest')
figure(6)
title('6h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Exchaust Temperature')
legend({'main graph','max(Sumpuknwths(:,6))','min(Sumpuknwths(:,6))'},'Location','southwest')
figure(7)
title('7h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Exchaust Pressure')
legend({'main graph','max(Sumpuknwths(:,7))','min(Sumpuknwths(:,7))'},'Location','southwest')
figure(8)
title('8h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Sea Side Temperature Inlet Condenser')
legend({'main graph','max(Sumpuknwths(:,8))','min(Sumpuknwths(:,8))'},'Location','southwest')
figure(9)
title('9h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Sea Side Temperature Outlet Condenser')
legend({'main graph','max(Sumpuknwths(:,9))','min(Sumpuknwths(:,9))'},'Location','southwest')
figure(10)
title('10h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Condenser Level')
legend({'main graph','max(Sumpuknwths(:,10))','min(Sumpuknwths(:,10))'},'Location','southwest')
figure(11)
title('11h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Sea Side Pressure inlet condenser pressure')
legend({'main graph','max(Sumpuknwths(:,11))','min(Sumpuknwths(:,11))'},'Location','southwest')
figure(12)
title('12h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Sea Side Pressure outlet condenser pressure')
legend({'main graph','max(Sumpuknwths(:,12))','min(Sumpuknwths(:,12))'},'Location','southwest')
figure(13)
title('13h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Condeser Temperature')
legend({'main graph','max(Sumpuknwths(:,13))','min(Sumpuknwths(:,13))'},'Location','southwest')
figure(14)
title('14h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Vacuum Condenser')
legend({'main graph','max(Sumpuknwths(:,14))','min(Sumpuknwths(:,14))'},'Location','southwest')
figure(15)
title('15h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('LP Steam Temperature')
legend({'main graph','max(Sumpuknwths(:,15))','min(Sumpuknwths(:,15))'},'Location','southwest')
figure(16)
title('16h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('LP Steam Pressure')
legend({'main graph','max(Sumpuknwths(:,16))','min(Sumpuknwths(:,16))'},'Location','southwest')
figure(17)
title('17h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('LP Steam Flow')
legend({'main graph','max(Sumpuknwths(:,17))','min(Sumpuknwths(:,17))'},'Location','southwest')
figure(18)
title('18h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('IP Steam Temperature')
legend({'main graph','max(Sumpuknwths(:,18))','min(Sumpuknwths(:,18))'},'Location','southwest')
figure(19)
title('19h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('IP Steam Pressure')
legend({'main graph','max(Sumpuknwths(:,19))','min(Sumpuknwths(:,19))'},'Location','southwest')
figure(20)
title('20h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('IP Steam Flow')
legend({'main graph','max(Sumpuknwths(:,20))','min(Sumpuknwths(:,20))'},'Location','southwest')
figure(21)
title('21h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('HP Steam Temperature')
legend({'main graph','max(Sumpuknwths(:,21))','min(Sumpuknwths(:,21))'},'Location','southwest')
figure(22)
title('22h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('HP Steam Pressure')
legend({'main graph','max(Sumpuknwths(:,22))','min(Sumpuknwths(:,22))'},'Location','southwest')
figure(23)
title('23h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('HP Steam Flow')
legend({'main graph','max(Sumpuknwths(:,23))','min(Sumpuknwths(:,23))'},'Location','southwest')
figure(24)
title('24h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Barometric Pressure')
legend({'main graph','max(Sumpuknwths(:,24))','min(Sumpuknwths(:,24))'},'Location','southwest')
figure(25)
title('25h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('GAS FUEL kg/h')
legend({'main graph','max(Sumpuknwths(:,25))','min(Sumpuknwths(:,25))'},'Location','southwest')
figure(26)
title('26h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('GAS FUEL Nm3/h')
legend({'main graph','max(Sumpuknwths(:,26))','min(Sumpuknwths(:,26))'},'Location','southwest')
figure(27)
title('27h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('LHV MJ/Nm3')
legend({'main graph','max(Sumpuknwths(:,27))','min(Sumpuknwths(:,27))'},'Location','southwest')
figure(28)
title('28h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('SELF CONSUMPTION(MW)')
legend({'main graph','max(Sumpuknwths(:,28))','min(Sumpuknwths(:,28))'},'Location','southwest')
figure(29)
title('29h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('KOSTOS AERIOU Eurw/Nm3')
legend({'main graph','max(Sumpuknwths(:,29))','min(Sumpuknwths(:,29))'},'Location','southwest')
figure(30)
title('30h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('HEAT_RATE(MJ/MWHR)')
legend({'main graph','max(Sumpuknwths(:,30))','min(Sumpuknwths(:,30))'},'Location','southwest')
figure(31)
title('31h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Piesh Exodou Strovilou Upshlhs')
legend({'main graph','max(Sumpuknwths(:,31))','min(Sumpuknwths(:,31))'},'Location','southwest')
figure(32)
title('32h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Thermokrasia Exodou Strovilou Upshlhs')
legend({'main graph','max(Sumpuknwths(:,32))','min(Sumpuknwths(:,32))'},'Location','southwest')
figure(33)
title('33h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Thermokrasia Exodou Strovilou Meshs')
legend({'main graph','max(Sumpuknwths(:,33))','min(Sumpuknwths(:,33))'},'Location','southwest')
figure(34)
title('34h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Thermokrasia Exodou Strovilou Xamhlhs')
legend({'main graph','max(Sumpuknwths(:,34))','min(Sumpuknwths(:,34))'},'Location','southwest')
figure(35)
title('35h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Piesh Exodou Strovilou Xamhlhs(mbar)')
legend({'main graph','max(Sumpuknwths(:,35))','min(Sumpuknwths(:,35))'},'Location','southwest')
figure(36)
title('36h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Sea Side Flow to Condenser(m^3/h)')
legend({'main graph','max(Sumpuknwths(:,36))','min(Sumpuknwths(:,36))'},'Location','southwest')
%figures HRSG
figure(37)
title('1h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nero Sumpuknwth')
legend({'main graph','max(HRSG(:,1))','min(HRSG(:,1))'},'Location','southwest')
figure(38)
title('2h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou meta tis antlies Sumpuknwmatos')
legend({'main graph','max(HRSG(:,2))','min(HRSG(:,2))'},'Location','southwest')
figure(39)
title('3h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh Nerou meta tis antlies sumpuknwmatos(bar)')
legend({'main graph','max(HRSG(:,3))','min(HRSG(:,3))'},'Location','southwest')
figure(40)
title('4h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh Nerou meta tis antlies sumpuknwmatos(t/h)')
legend({'main graph','max(HRSG(:,4))','min(HRSG(:,4))'},'Location','southwest')
figure(41)
title('5h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou prin ton Preheater(HSRG)')
legend({'main graph','max(HRSG(:,5))','min(HRSG(:,5))'},'Location','southwest')
figure(42)
title('6h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou meta ton Preheater(HSRG)')
legend({'main graph','max(HRSG(:,6))','min(HRSG(:,6))'},'Location','southwest')
figure(43)
title('7h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou sto FWT')
legend({'main graph','max(HRSG(:,7))','min(HRSG(:,7))'},'Location','southwest')
figure(44)
title('8h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh Nerou sto FWT')
legend({'main graph','max(HRSG(:,8))','min(HRSG(:,8))'},'Location','southwest')
figure(45)
title('9h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh Nerou meta ton Preheater sto doxeio LP')
legend({'main graph','max(HRSG(:,9))','min(HRSG(:,9))'},'Location','southwest')
figure(46)
title('10h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou Doxeio LP')
legend({'main graph','max(HRSG(:,10))','min(HRSG(:,10))'},'Location','southwest')
figure(47)
title('11h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh Nerou Doxeio LP')
legend({'main graph','max(HRSG(:,11))','min(HRSG(:,11))'},'Location','southwest')
figure(48)
title('12h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta ton Superheater LP')
legend({'main graph','max(HRSG(:,12))','min(HRSG(:,12))'},'Location','southwest')
figure(49)
title('13h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh meta ton Superheater LP')
legend({'main graph','max(HRSG(:,13))','min(HRSG(:,13))'},'Location','southwest')
figure(50)
title('14h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh meta ton Superheater LP')
legend({'main graph','max(HRSG(:,14))','min(HRSG(:,14))'},'Location','southwest')
figure(51)
title('15h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh meta Trofodosia Antlia Meshs Pieshs')
legend({'main graph','max(HRSG(:,15))','min(HRSG(:,15))'},'Location','southwest')
figure(52)
title('16h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta Trofodosia Antlia Meshs Pieshs')
legend({'main graph','max(HRSG(:,16))','min(HRSG(:,16))'},'Location','southwest')
figure(53)
title('17h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta Economizer Mesh Piesh')
legend({'main graph','max(HRSG(:,17))','min(HRSG(:,17))'},'Location','southwest')
figure(54)
title('18h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh meta Economizer Mesh Piesh')
legend({'main graph','max(HRSG(:,18))','min(HRSG(:,18))'},'Location','southwest')
figure(55)
title('19h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh pros thermansh aeriou')
legend({'main graph','max(HRSG(:,19))','min(HRSG(:,19))'},'Location','southwest')
figure(56)
title('20h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh Doxeiou Meshs Pieshs')
legend({'main graph','max(HRSG(:,20))','min(HRSG(:,20))'},'Location','southwest')
figure(57)
title('21h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Doxeiou Meshs Pieshs')
legend({'main graph','max(HRSG(:,21))','min(HRSG(:,21))'},'Location','southwest')
figure(58)
title('22h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia atmou meta Superheater')
legend({'main graph','max(HRSG(:,22))','min(HRSG(:,22))'},'Location','southwest')
figure(59)
title('23h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh atmou meta Superheater')
legend({'main graph','max(HRSG(:,23))','min(HRSG(:,23))'},'Location','southwest')
figure(60)
title('24h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta thn enwsh (IP+CRH)')
legend({'main graph','max(HRSG(:,24))','min(HRSG(:,24))'},'Location','southwest')
figure(61)
title('25h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta thn enwsh (IP+CRH) kai meta Reheater')
legend({'main graph','max(HRSG(:,25))','min(HRSG(:,25))'},'Location','southwest')
figure(62)
title('26h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh meta thn enwsh (IP+CRH) kai meta Reheater')
legend({'main graph','max(HRSG(:,26))','min(HRSG(:,26))'},'Location','southwest')
figure(63)
title('27h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh meta trofodosia antlia pros upshlh piesh')
legend({'main graph','max(HRSG(:,27))','min(HRSG(:,27))'},'Location','southwest')
figure(64)
title('28h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh meta trofodosia antlia pros upshlh piesh')
legend({'main graph','max(HRSG(:,28))','min(HRSG(:,28))'},'Location','southwest')
figure(65)
title('29h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta trofodosia antlia pros upshlh piesh')
legend({'main graph','max(HRSG(:,29))','min(HRSG(:,29))'},'Location','southwest')
figure(66)
title('30h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou meta Economizer Ypshlhs')
legend({'main graph','max(HRSG(:,30))','min(HRSG(:,30))'},'Location','southwest')
figure(67)
title('31h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia doxeiou Ypshlhs Pieshs')
legend({'main graph','max(HRSG(:,31))','min(HRSG(:,31))'},'Location','southwest')
figure(68)
title('32h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh doxeiou Ypshlhs Pieshs')
legend({'main graph','max(HRSG(:,32))','min(HRSG(:,32))'},'Location','southwest')
figure(69)
title('33h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Ypshlhs meta No1 Superheater Ypshlhs')
legend({'main graph','max(HRSG(:,33))','min(HRSG(:,33))'},'Location','southwest')
figure(70)
title('34h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Ypshlhs meta No1 Superheater Ypshlhs kai meta Desuperheater')
legend({'main graph','max(HRSG(:,34))','min(HRSG(:,34))'},'Location','southwest')
figure(71)
title('35h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Atmou HP pros Strovilo')
legend({'main graph','max(HRSG(:,35))','min(HRSG(:,35))'},'Location','southwest')
figure(72)
title('36h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh Atmou HP pros Strovilo')
legend({'main graph','max(HRSG(:,36))','min(HRSG(:,36))'},'Location','southwest')
figure(73)
title('37h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh Atmou HP pros Strovilo')
legend({'main graph','max(HRSG(:,37))','min(HRSG(:,37))'},'Location','southwest')
%figures AERIOSTROVILOS
figure(74)
title('1h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Roh Aeriou kg/s')
legend({'main graph','max(AERIOSTROVILOS(:,1))','min(AERIOSTROVILOS(:,1))'},'Location','southwest')
figure(75)
title('2h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Piesh meta Sumpiesth(bar)')
legend({'main graph','max(AERIOSTROVILOS(:,2))','min(AERIOSTROVILOS(:,2))'},'Location','southwest')
figure(76)
title('3h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia meta Sumpiesth')
legend({'main graph','max(AERIOSTROVILOS(:,3))','min(AERIOSTROVILOS(:,3))'},'Location','southwest')
figure(77)
title('4h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Piesh Eisodos Sumpiesth(mbar)')
legend({'main graph','max(AERIOSTROVILOS(:,4))','min(AERIOSTROVILOS(:,4))'},'Location','southwest')
figure(78)
title('5h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia Eisodos Sumpiesth')
legend({'main graph','max(AERIOSTROVILOS(:,5))','min(AERIOSTROVILOS(:,5))'},'Location','southwest')
figure(79)
title('6h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia kausaeriwn eisodos levhta')
legend({'main graph','max(AERIOSTROVILOS(:,6))','min(AERIOSTROVILOS(:,6))'},'Location','southwest')
figure(80)
title('7h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia kausaeriwn exodos levhta')
legend({'main graph','max(AERIOSTROVILOS(:,7))','min(AERIOSTROVILOS(:,7))'},'Location','southwest')
figure(81)
title('8h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('ROH AERA EISODOS SUMPIESTH kg/s')
legend({'main graph','max(AERIOSTROVILOS(:,8))','min(AERIOSTROVILOS(:,8))'},'Location','southwest')
figure(82)
title('9h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('ROH KAUSAERIWN kg/s')
legend({'main graph','max(AERIOSTROVILOS(:,9))','min(AERIOSTROVILOS(:,9))'},'Location','southwest')
figure(83)
title('10h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia Eisodou Strovilou')
legend({'main graph','max(AERIOSTROVILOS(:,10))','min(AERIOSTROVILOS(:,10))'},'Location','southwest')
figure(84)
title('11h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Piesh Exodou Strovilou')
legend({'main graph','max(AERIOSTROVILOS(:,11))','min(AERIOSTROVILOS(:,11))'},'Location','southwest')
figure(85)
title('12h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia Exodou Strovilou')
legend({'main graph','max(AERIOSTROVILOS(:,12))','min(AERIOSTROVILOS(:,12))'},'Location','southwest')















































