for i=1:36
    figure(i)
plot(Sumpuknwths(:,i))
hline1 = refline([0 max(Sumpuknwths(:,i))]);
hline1.Color='r';
hline2 = refline([0 min(Sumpuknwths(:,i))]);
hline2.Color= 'y';
end
for i=1:37
    figure(i+36)
    plot(HRSG(:,i))
hline1 = refline([0 max(HRSG(:,i))]);
hline1.Color='r';
hline2 = refline([0 min(HRSG(:,i))]);
hline2.Color= 'y';
end
for i=1:12
    figure(i+73)
    plot(AERIOSTROVILOS(:,i))
hline1 = refline([0 max(AERIOSTROVILOS(:,i))]);
hline1.Color='r';
hline2 = refline([0 min(AERIOSTROVILOS(:,i))]);
hline2.Color= 'y';
end
%figures Sumpuknwths
figure(1)
title('1h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Plant MW(NET)')
figure(2)
title('2h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('GasTurbine(MW)')
figure(3)
title('3h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('SteamTurbine(MW)')
figure(4)
title('4h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Ambient Humidity(%)')
figure(5)
title('5h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Ambient Temperature')
figure(6)
title('6h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Exchaust Temperature')
figure(7)
title('7h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Exchaust Pressure')
figure(8)
title('8h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Sea Side Temperature Inlet Condenser')
figure(9)
title('9h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Sea Side Temperature Outlet Condenser')
figure(10)
title('10h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Condenser Level')
figure(11)
title('11h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Sea Side Pressure inlet condenser pressure')
figure(12)
title('12h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Sea Side Pressure outlet condenser pressure')
figure(13)
title('13h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Condeser Temperature')
figure(14)
title('14h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Vacuum Condenser')
figure(15)
title('15h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('LP Steam Temperature')
figure(16)
title('16h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('LP Steam Pressure')
figure(17)
title('17h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('LP Steam Flow')
figure(18)
title('18h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('IP Steam Temperature')
figure(19)
title('19h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('IP Steam Pressure')
figure(20)
title('20h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('IP Steam Flow')
figure(21)
title('21h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('HP Steam Temperature')
figure(22)
title('22h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('HP Steam Pressure')
figure(23)
title('23h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('HP Steam Flow')
figure(24)
title('24h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Barometric Pressure')
figure(25)
title('25h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('GAS FUEL kg/h')
figure(26)
title('26h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('GAS FUEL Nm3/h')
figure(27)
title('27h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('LHV MJ/Nm3')
figure(28)
title('28h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('SELF CONSUMPTION(MW)')
figure(29)
title('29h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('KOSTOS AERIOU Eurw/Nm3')
figure(30)
title('30h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('HEAT_RATE(MJ/MWHR)')
figure(31)
title('31h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Piesh Exodou Strovilou Upshlhs')
figure(32)
title('32h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Thermokrasia Exodou Strovilou Upshlhs')
figure(33)
title('33h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Thermokrasia Exodou Strovilou Meshs')
figure(34)
title('34h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Thermokrasia Exodou Strovilou Xamhlhs')
figure(35)
title('35h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Piesh Exodou Strovilou Xamhlhs(mbar)')
figure(36)
title('36h sthlh Sumpuknwths')
xlabel('Observations') 
ylabel('Sea Side Flow to Condenser(m^3/h)')
%figures HRSG
figure(37)
title('1h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nero Sumpuknwth')
figure(38)
title('2h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou meta tis antlies Sumpuknwmatos')
figure(39)
title('3h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh Nerou meta tis antlies sumpuknwmatos(bar)')
figure(40)
title('4h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh Nerou meta tis antlies sumpuknwmatos(t/h)')
figure(41)
title('5h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou prin ton Preheater(HSRG)')
figure(42)
title('6h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou meta ton Preheater(HSRG)')
figure(43)
title('7h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou sto FWT')
figure(44)
title('8h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh Nerou sto FWT')
figure(45)
title('9h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh Nerou meta ton Preheater sto doxeio LP')
figure(46)
title('10h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou Doxeio LP')
figure(47)
title('11h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh Nerou Doxeio LP')
figure(48)
title('12h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta ton Superheater LP')
figure(49)
title('13h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh meta ton Superheater LP')
figure(50)
title('14h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh meta ton Superheater LP')
figure(51)
title('15h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh meta Trofodosia Antlia Meshs Pieshs')
figure(52)
title('16h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta Trofodosia Antlia Meshs Pieshs')
figure(53)
title('17h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta Economizer Mesh Piesh')
figure(54)
title('18h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh meta Economizer Mesh Piesh')
figure(55)
title('19h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh pros thermansh aeriou')
figure(56)
title('20h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh Doxeiou Meshs Pieshs')
figure(57)
title('21h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Doxeiou Meshs Pieshs')
figure(58)
title('22h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia atmou meta Superheater')
figure(59)
title('23h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh atmou meta Superheater')
figure(60)
title('24h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta thn enwsh (IP+CRH)')
figure(61)
title('25h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta thn enwsh (IP+CRH) kai meta Reheater')
figure(62)
title('26h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh meta thn enwsh (IP+CRH) kai meta Reheater')
figure(63)
title('27h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh meta trofodosia antlia pros upshlh piesh')
figure(64)
title('28h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh meta trofodosia antlia pros upshlh piesh')
figure(65)
title('29h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia meta trofodosia antlia pros upshlh piesh')
figure(66)
title('30h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Nerou meta Economizer Ypshlhs')
figure(67)
title('31h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia doxeiou Ypshlhs Pieshs')
figure(68)
title('32h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh doxeiou Ypshlhs Pieshs')
figure(69)
title('33h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Ypshlhs meta No1 Superheater Ypshlhs')
figure(70)
title('34h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Ypshlhs meta No1 Superheater Ypshlhs kai meta Desuperheater')
figure(71)
title('35h sthlh HRSG')
xlabel('Observations') 
ylabel('Thermokrasia Atmou HP pros Strovilo')
figure(72)
title('36h sthlh HRSG')
xlabel('Observations') 
ylabel('Piesh Atmou HP pros Strovilo')
figure(73)
title('37h sthlh HRSG')
xlabel('Observations') 
ylabel('Roh Atmou HP pros Strovilo')
%figures AERIOSTROVILOS
figure(74)
title('1h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Roh Aeriou kg/s')
figure(75)
title('2h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Piesh meta Sumpiesth(bar)')
figure(76)
title('3h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia meta Sumpiesth')
figure(77)
title('4h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Piesh Eisodos Sumpiesth(mbar)')
figure(78)
title('5h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia Eisodos Sumpiesth')
figure(79)
title('6h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia kausaeriwn eisodos levhta')
figure(80)
title('7h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia kausaeriwn exodos levhta')
figure(81)
title('8h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('ROH AERA EISODOS SUMPIESTH kg/s')
figure(82)
title('9h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('ROH KAUSAERIWN kg/s')
figure(83)
title('10h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia Eisodou Strovilou')
figure(84)
title('11h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Piesh Exodou Strovilou')
figure(85)
title('12h sthlh AERIOSTROVILOS')
xlabel('Observations') 
ylabel('Thermokrasia Exodou Strovilou')















































